### ISSUE TITLE
Mình thấy có lỗi xíu trong phần Upload image with multer

### ISSUE THREAD

**Issue by inuyashaaa** [picosix/p6-static-example#1]
Trong phần sử dụng -> 2. Tạo một "api endpoint" :
Chỗ `destination(req, file, cb) {
    cb(null, `${path.resolve(__dirname, '..', 'resource')}`);
  }`
Cần sửa thành `destination(req, file, cb) {
    cb(null, `${path.resolve(__dirname, 'public/resource')}`);
  }`

**Comment by picosix** [comment]
+1 Cám ơn bạn :D Mình đã update lại rồi

**Comment by inuyashaaa** [comment]
Tuts này của anh rất hay. Em có thể xin facebook hay skype của anh được không ạ :D

**Comment by picosix** [comment]
Skype của mình: tuan.nguyen930708@hotmail.com hoặc picosix@hotmail.com

**Comment by inuyashaaa** [comment]
Anh ơi phần anh update lại vẫn bị lỗi ạ, chỉ còn `__dirname, 'public/resource'` thôi ạ.
Với thêm một cái nữa là sau khi chỉnh config sửa lại file `index.js` thì chỗ `type => type.trim()` mới đúng ạ

**Comment by picosix** [comment]
Mình quên cập nhật phần hướng dẫn :D cod thì mình sửa rồi. Lần sau bạn cứ mạnh dạng tạo pull request :D

**Comment by inuyashaaa** [comment]
Đã rõ :3
