### ISSUE TITLE
Lỗi 403 Forbidden (Phần Docker app)

### ISSUE THREAD

**Issue by inuyashaaa** [picosix/p6-static-example#2]
Khi em làm đến phần Docker khi hoàn thành em truy cập vào trang index thì bình thường
![docker1](https://user-images.githubusercontent.com/17411092/34849033-8f60f2d4-f753-11e7-93c7-53fccd3642a9.png)
Nhưng đến khi vào endpoint test thì bị lỗi 403 Forbidden này ạ
![docker2](https://user-images.githubusercontent.com/17411092/34849070-bab0c43c-f753-11e7-9184-f21fd7420cec.png)
Không biết lỗi này là do gì vậy anh?

**Comment by inuyashaaa** [comment]
Với thêm một chút là Docs cho phần này anh đang bị duplicate hướng dẫn `Chạy nginx container` :D

**Comment by picosix** [comment]
Vì phần"Chạy nginx container" bị duplicate nên có lẽ bạn đã chạy nhầm config cũ :D Mình đã cập nhật document lại rồi, bạn nên xoá hết docker container và chạy lại từ đầu.

Thank bạn :)

**Comment by inuyashaaa** [comment]
Em đã xóa hết docker container đi và chạy laị rồi mà vẫn bị lỗi đấy anh ạ :(

**Comment by picosix** [comment]
Bạn nên xoá cả file `docker/nginx-config/default.conf` và làm lại, vì mình có sửa trong file đó
